# Generated by Django 4.2.1 on 2023-05-31 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('chore', models.CharField(choices=[('C', 'Cleaning'), ('H', 'Hypermatter Fuel Refill'), ('A', 'AMMO Recharge'), ('S', 'Shield Recharge')], default='H', max_length=1)),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.ship')),
            ],
        ),
    ]
