# Generated by Django 4.2.1 on 2023-06-01 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_crew_alter_maintenance_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ship',
            name='crew',
        ),
    ]
