# Generated by Django 4.2.1 on 2023-06-01 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_ship_crew'),
    ]

    operations = [
        migrations.AddField(
            model_name='ship',
            name='crew',
            field=models.ManyToManyField(to='main_app.crew'),
        ),
    ]
